# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpc',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
