# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161214_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='localidad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
