# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userp_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='mensaje',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userp',
            name='otros',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userp',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
