# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170101_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='exp',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
