# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170216_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='file',
        ),
    ]
