# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='file',
            field=models.FileField(blank=True, upload_to=users.models.upload_location),
        ),
    ]
