# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170306_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userp',
            old_name='Carrera',
            new_name='carrera',
        ),
        migrations.AddField(
            model_name='userp',
            name='sexo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
