# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userp_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
