# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170314_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userp',
            name='salario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
