# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_auto_20161208_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicado',
            name='apli_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
