# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpc_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpc',
            name='company',
            field=models.BooleanField(),
        ),
    ]
