# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161212_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='file',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
