# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='file',
            field=models.FileField(upload_to=users.models.upload_location),
        ),
    ]
