# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='otros',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='telefono',
        ),
    ]
