# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170217_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='Carrera',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userp',
            name='ar_exp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userp',
            name='ar_int',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userp',
            name='idioma',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
