# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170306_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='cedula',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
