# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userp_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='idioma',
            field=models.TextField(blank=True),
        ),
    ]
