# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170306_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='cat_licen',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userp',
            name='licencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userp',
            name='universidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
