# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170316_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='cat_licen',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
