# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170321_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='pais_apli',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
