# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180618_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='ar_exp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='ar_int',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='experiencia',
            field=models.TextField(blank=True),
        ),
    ]
