# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180929_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='edad2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userp',
            name='fec_nac',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
