# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicado',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicado',
            name='estatus2',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aplicado',
            name='aplico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.Vacante'),
        ),
    ]
