# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_auto_20170306_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicado',
            name='comentario_int',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
