# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0007_aplicado_comentario_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicado',
            name='com_interno',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
