# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0008_aplicado_com_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicado',
            name='comentario_int',
        ),
    ]
