# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0013_auto_20170326_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacante',
            options={'ordering': ['-creatd_date']},
        ),
        migrations.AddField(
            model_name='vacante',
            name='pais',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
