# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0015_aplicado_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creatd_date', models.DateTimeField(auto_now_add=True)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
