# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0016_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='compania2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacantes.Compania'),
            preserve_default=False,
        ),
    ]
